version: '3'
services:
    blog:
        build: .
        image: blog
        ports:
            - "5000:5000"
        volumes: 
            - /home/yyr/deploy-flask-app:/code/blog
        privileged: true
        restart: always
