version: '3'
services:
    blog:
        build: .
        image: blog
        ports:
            - "5001:5000"
        volumes: 
            - /home/yyr/docker-flask-app:/code/blog
        privileged: true
        restart: always
